# Generated by Django 4.0.8 on 2022-12-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('invoice_ident', models.CharField(db_column='InvoiceIdent', max_length=39)),
                ('invoice_number', models.CharField(db_column='InvoiceNumber', max_length=25)),
                ('unbilled_wip', models.DecimalField(db_column='UnbilledWIP', decimal_places=2, max_digits=9, null=True)),
                ('unappliedprog_amt', models.DecimalField(db_column='OpenAmount', decimal_places=2, max_digits=9)),
                ('client_ident', models.CharField(db_column='ClientIdent', max_length=39)),
                ('client_name', models.CharField(db_column='ClientName', max_length=255)),
                ('client_full_id', models.CharField(db_column='ClientIdSubId', max_length=50)),
                ('is_deactive', models.BooleanField(db_column='IsDeactivated', default=False)),
                ('audit_partner', models.CharField(db_column='AuditPartner', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tblProgressInvoice',
            },
        ),
        migrations.CreateModel(
            name='ProgessInvoiceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('project_ident', models.CharField(blank=True, db_column='ProjectIdent', max_length=39, null=True)),
                ('project_name', models.CharField(db_column='ProjectName', max_length=255)),
                ('project_status', models.CharField(blank=True, db_column='ProjectStatus', max_length=255, null=True)),
                ('allocated_amount', models.DecimalField(db_column='AppliedAmount', decimal_places=2, default=0, max_digits=9)),
                ('is_alloc_active', models.BooleanField(db_column='IsActive', default=True)),
                ('is_auto_applied_amount', models.BooleanField(db_column='IsAutoApplied', default=True)),
                ('progress_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocs', to='progress_invoice.progressinvoice')),
            ],
            options={
                'db_table': 'tblProgressInvoiceAllocation',
            },
        ),
    ]
