# Generated by Django 4.0.8 on 2022-12-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('client_ident', models.CharField(db_column='ClientIdent', max_length=39)),
                ('client_name', models.CharField(db_column='ClientSortName', max_length=255)),
                ('client_full_id', models.CharField(max_length=50, verbose_name='Client ID')),
            ],
            options={
                'db_table': 'tblClient',
                'ordering': ('client_name',),
            },
        ),
        migrations.RemoveField(
            model_name='progressinvoice',
            name='client_full_id',
        ),
        migrations.RemoveField(
            model_name='progressinvoice',
            name='client_ident',
        ),
        migrations.RemoveField(
            model_name='progressinvoice',
            name='client_name',
        ),
        migrations.AddField(
            model_name='progressinvoice',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='prog_invs', to='progress_invoice.client'),
            preserve_default=False,
        ),
    ]
