# Generated by Django 4.0.8 on 2023-02-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_invoice', '0002_client_remove_progressinvoice_client_full_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progessinvoiceallocation',
            name='is_auto_applied_amount',
            field=models.BooleanField(db_column='IsAutoApplied', default=False),
        ),
    ]
